### ISSUE TITLE
Unable to install module

### ISSUE THREAD

**Issue by DeanGross** [microsoft/secmgmt-open-powershell#11]
# Steps to reproduce

Install-Module -Name SecMgmt -AllowClobber -Scope AllUsers

## Expected behavior

i expected the module to be installed

## Actual behavior

I get the following 

PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'SecMgmt'. Try Get-PSRepository to see all available registered module repositories.
At C:\Users\dgross\Documents\WindowsPowerShell\Modules\PowerShellGet\2.2.4.1\PSModule.psm1:9709 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by isaiahwilliams** [comment]
@DeanGross this issue should be be resolved now. If you run the following it will install the module.

```powershell
Install-Module SecMgmt
```

Please let us know if you have any feature requests or issues.

**Comment by isaiahwilliams** [comment]
This issue has been resolved, please let us know if you have any trouble with installing the module.
